[package]
name = "ligen-c"
version = "0.1.0"
authors = ["Danilo Guanabara <danguafer@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
ligen = { path = "../ligen" }
ligen-core = { path = "../ligen-core" }
