[package]
name = "ligen-c"
version = "0.1.0"
authors = ["Danilo Guanabara <danguafer@gmail.com>"]
edition = "2018"
workspace = "../"

[lib]
proc-macro = true

[dependencies]
ligen-c-core = { git = "https://github.com/sensorial-systems/ligen-c/", branch = "main" }

